"""
shapes.py
─────────
Special-case shape handlers for shapes where the LLM generates
unreliable CadQuery code.

Why is this needed?
The LLM sometimes uses .cone() which does not exist in CadQuery,
or generates a revolve() call with the wrong axis arguments.
For cones, we detect the request and use a known-correct template
instead of trusting the LLM's output.

This pattern can be extended for other problematic shapes in future.
"""

import re
import textwrap
from typing import Optional


def is_cone_request(description: str) -> bool:
    """
    Return True if the user prompt is asking for a cone shape.

    Args:
        description: Natural language prompt from the user

    Returns:
        bool: True if the prompt contains cone-related keywords
    """
    keywords: list[str] = ["cone", "conical"]
    return any(kw in description.lower() for kw in keywords)


def extract_cone_dimensions(description: str, llm_code: str) -> tuple[float, float]:
    """
    Extract base radius and height for a cone from the description or LLM code.

    Strategy:
    1. Try regex on the user description first (most reliable)
    2. Fall back to parsing variable assignments in the LLM-generated code
    3. If both fail, use safe defaults (25mm radius, 50mm height)

    Args:
        description: Original user prompt
        llm_code:    Code generated by the LLM (used as fallback)

    Returns:
        tuple[float, float]: (base_radius, height) in millimetres
    """
    # ── Step 1: Try the description ───────────────────────────
    radius_match = re.search(
        r'base\s+radius\s+(?:of\s+)?(\d+(?:\.\d+)?)\s*mm', description, re.IGNORECASE
    ) or re.search(
        r'radius\s+(?:of\s+)?(\d+(?:\.\d+)?)\s*mm', description, re.IGNORECASE
    )
    height_match = re.search(
        r'height\s+(?:of\s+)?(\d+(?:\.\d+)?)\s*mm', description, re.IGNORECASE
    ) or re.search(
        r'(\d+(?:\.\d+)?)\s*mm\s+(?:tall|high)', description, re.IGNORECASE
    )

    base_r: Optional[float] = float(radius_match.group(1)) if radius_match else None
    height: Optional[float] = float(height_match.group(1)) if height_match else None

    # ── Step 2: Fall back to parsing LLM variable assignments ─
    if base_r is None or height is None:
        for line in llm_code.splitlines():
            line = line.strip()
            if re.match(r'^(base_r|base_radius|radius|r)\s*=\s*[\d.]+', line) and base_r is None:
                base_r = float(re.search(r'[\d.]+', line.split('=')[1]).group())
            if re.match(r'^(height|h)\s*=\s*[\d.]+', line) and height is None:
                height = float(re.search(r'[\d.]+', line.split('=')[1]).group())

    # ── Step 3: Safe defaults ──────────────────────────────────
    return base_r or 25.0, height or 50.0


def build_cone_code(base_r: float, height: float) -> str:
    """
    Return a guaranteed-correct CadQuery cone script.

    Uses the revolve method with an explicit axis — this is the only
    reliable way to create a cone in CadQuery. The LLM's version is
    discarded and replaced with this template.

    Args:
        base_r: Base radius of the cone in millimetres
        height: Height of the cone in millimetres

    Returns:
        str: Complete, executable CadQuery Python script
    """
    return textwrap.dedent(f"""
        import cadquery as cq
        base_r = {base_r}
        height = {height}
        result = (
            cq.Workplane("XZ")
            .moveTo(0, 0)
            .lineTo(base_r, 0)
            .lineTo(0, height)
            .close()
            .revolve(360, (0, 0), (0, 1))
        )
    """).strip()